parameters:
    database.driver:        mysql
    database.host:          localhost
    database.port:          3306
    database.name:          dewauwel
    database.user:          dewauwel
    database.password:      bgp453

    kernel.debug:           true
    kernel.charset:         'utf-8'

    fork.debug_email:       lorenz@24street.be
    fork.debug_message:     'Internal error.'
    fork.version:           '3.6.6'

    site.protocol:          http
    site.domain:            jhdewauwel.dev
    site.default_title:     Fork CMS
    site.multilanguage:     false
    site.default_language:  nl
    site.path_www:          %kernel.root_dir%/..
    site.path_library:      %site.path_www%/library

    action.group_tag:       \@actiongroup
    action.rights_level:    7
